---
title: "Table 1 Results"
author: "Jacob Jameson"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=F}
# Load packages necessary for preparing final data
library(tidyverse)
library(haven)
library(labelled)
library(scales)
library(survey)
library(gtsummary)
library(gridExtra)

theme_gtsummary_journal(journal = "jama")
theme_gtsummary_compact()

# Create and prepare wave 1 and wave 4 data
data_path <- '~/Desktop/Add Health Substance Use Project/'

final.df <- read.csv(paste0(data_path, 'Data/Final.csv'))
network <- read.csv(paste0(data_path, 'Data/network.csv'))
final.df <- merge(final.df, network, by='aid')
sum(final.df$in_sample)

```

\newpage

```{r, message=F, warning=F}
t1.vars <- c("race", 'pseudo.gpa', 'sespc_al', 'nhood1_d', 
             "w1.cigarettes", "w1.marijuana", 
             "w1.drunk", "w1.recreational", "w4.cigarettes", "w4.marijuana", 
             "w4.drunk", "w4.recreational", "w4.prescription")


final.df %>% filter(in_sample == 1) %>%
    select(one_of(t1.vars), school_self) %>%
    tbl_summary(by = school_self,
                type = all_continuous() ~ "continuous2",
                statistic = all_continuous() ~ c("{mean} ({sd})"),
                missing_text = "(Missing)") %>% 
    add_p(pvalue_fun = ~style_pvalue(.x, digits = 2),
          test = list(all_continuous() ~ "aov",
                     all_categorical() ~ "chisq.test")) %>%
    add_overall() %>% modify_header(label ~ "**Variable**") %>%
    modify_caption("**Patient Characteristics (unweighted)**") %>%
    bold_labels()
```




```{r, message=F, warning=F}

final.df <- final.df %>% filter(in_sample == 1) 
final.weighted <- svydesign(id=~psuscid, strata=~region,
                            weights=~gswgt4_2, data=final.df, nest=TRUE)

# Define subgroup and calculate estimates in table
final.weighted %>%
  tbl_svysummary(
    by = school_self, 
    type = all_continuous() ~ "continuous2",
                statistic = 
                all_continuous() ~ c("{mean} ({sd})"),
                missing = "always",
    include = c(one_of(t1.vars), school_self)) %>%
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 2),
        test = list(all_continuous() ~ "svy.kruskal.test",
         all_categorical() ~ "svy.chisq.test")) %>%
  add_overall() %>%
  modify_header(label ~ "**Variable**") %>%
  modify_caption("**Table 1. Patient Characteristics (weighted)**") %>%
  bold_labels()
```

